### ISSUE TITLE
Create JUnit Test Cases

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2122S2-CS2113T-T09-2/tp#103]

**Comment by Musfirahe0556596** [comment]
#102 have JUnit test cases for the create and list plan.

**Comment by Musfirahe0556596** [comment]
#104 have JUnit test cases for searching for plans and exercise.

**Comment by Musfirahe0556596** [comment]
#154 have additional JUnit test cases for the create plan method.

**Comment by alanlowzies** [comment]
PR #156 has more JUnit test cases for general coverage expansion.

**Comment by emilysim00** [comment]
#234 has Junit test case for schedule features

**Comment by Musfirahe0556596** [comment]
#251 has Junit test cases for WorkoutCommand and PlanCommand
