### ISSUE TITLE
Color display on different operating system

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2122S2-CS2113T-T09-2/tp#169]
java -jar WerkIt.jar | Out-Host

**Comment by alanlowzies** [comment]
https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701

Using the Windows Terminal app made by Microsoft will allow Powershell to show the colours as intended.

**Comment by Musfirahe0556596** [comment]
For reference that it works:

![image](https://user-images.githubusercontent.com/69451253/160891806-b66067f7-a50a-49e8-8e47-6550f24d396e.png)
