### ISSUE TITLE
Deleting a Plan Does Not Remove It From the Schedule List

### ISSUE THREAD

**Issue by alanlowzies** [AY2122S2-CS2113T-T09-2/tp#170]
This is a bug where when a plan is deleted, the deleted plan still remains in the schedule.

Expected action: delete plan > check for days in schedule that has the deleted plan > for days that has this plan, clear that plan for that day.

**Comment by Musfirahe0556596** [comment]
#172  has part of this bug fix. Here, the upon deleting a workout, the deleteWorkout will also cascade to delete plans which has that workout - aka by calling deletePlan.
