### ISSUE TITLE
Review comments for your DG

### ISSUE THREAD

**Issue by okkhoy** [AY2122S2-CS2113T-T09-2/tp#175]
In general, there are not too many "syntax problems" in the UML diagrams. I have mentioned a couple of issues I found below.

1. Aren't these some of the main things related to your product? Please update soon.
![image](https://user-images.githubusercontent.com/1023494/160958025-8bef3391-58d4-4ccb-b255-349eb40cb3ad.png)

2. A few issues with the class diagram below
![image](https://user-images.githubusercontent.com/1023494/160958158-2730b322-92d7-4959-93fc-29c6d2fdc1f7.png)
    1. Missing navigability information makes this design vague
    2. Non-standard UML. Please check how to remove the decorators in PlantUML (applicable to the other class diagrams in the DG too)
    
3. Perhaps a better name?
![image](https://user-images.githubusercontent.com/1023494/160958345-ec6582af-fdbf-406b-b0c4-2e1679b6775a.png)

4. You can describe the involvement of user in words and eliminate the user entity (1) as calls like this (2) can get confusing.
![image](https://user-images.githubusercontent.com/1023494/160958491-ca92647f-c436-492f-81c9-2caf703def9c.png)

5. Consider removing the bottom markers for decluttering purposes.
![image](https://user-images.githubusercontent.com/1023494/160958573-db8e4393-97a8-401f-967a-4583994d55f4.png)

6. You can use the ref frames more effectively to simply the sequence diagram. E.g., there are two entries for UI, indicating that it may be a candidate for 2 SD rather than 1 (or use ref frames) (Applies to workout /delete too)
![image](https://user-images.githubusercontent.com/1023494/160958726-e4544451-230d-4028-9103-ff6252404c45.png)

7. It is OK to skip exception handling in the SD (as there are no standard notations for exceptions in SD). You can mention that in the text.
![image](https://user-images.githubusercontent.com/1023494/160958847-1e6fe8b4-d54d-4a4d-98d9-6f956a6fe2d4.png)

8. [Nitpick/non-issue] why is your headings smaller than the main text? 😄 
![image](https://user-images.githubusercontent.com/1023494/160958942-4a14e249-db23-4bec-b4dc-098451b1b71a.png)

9. The title of the diagram is a bit confusing. Not sure what I should expect from the diagram. In particular, should the class name be `WorkoutListCommand`
![image](https://user-images.githubusercontent.com/1023494/160959216-e56e6fe5-e2b2-4f15-93d1-089a81e03b4f.png)

10. Too small to read (particularly when printed to pdf)
![image](https://user-images.githubusercontent.com/1023494/160959684-335ce659-722b-415e-93e3-a97917452175.png)

11. There seems to be a bit of imbalance in the way you represent the information. Too many SD compared to too few class diagrams (letting a new developer know of the structure is equally important as the behavior).

**Comment by alanlowzies** [comment]
For Point 8, I think those headers are quite nested (Level 6 if I'm not wrong). We did notice that, but we're not sure if there's a way for us to explicitly modify the font size for the headers. 😬

**Comment by okkhoy** [comment]
Maybe got to do with the stylesheet adopted.

**Comment by alanlowzies** [comment]
Okay, we'll try to see if we can make the font size bigger. Thanks for the tip, Prof :)
