### ISSUE TITLE
[PE-D] exercise list command - Unknown Symbols

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-2/tp#187]
When running the list command, strange unreadable symbols appeared on the console, making me not understand some lines.

Expected output from User Guide:

![image.png](https://raw.githubusercontent.com/YitHien/ped/main/files/13960e6d-b85c-4290-af10-a067f22eca10.png)

Output from console:

![image.png](https://raw.githubusercontent.com/YitHien/ped/main/files/a38c0524-7765-40c7-bf2d-754ae07ce6fe.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YitHien/ped#2

**Comment by Musfirahe0556596** [comment]
Fixed in #225 , stated in UG that users should use Windows Terminal for colours to be displayed.
