### ISSUE TITLE
[PE-D] wording

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-2/tp#189]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/939935fc-0cdb-4e75-88b1-cc8379682aae.png)
can be better worded:

"All workouts in the current list will be listed, as shown above with a list of 3 workouts."

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: SeanHoWB/ped#5

**Comment by Musfirahe0556596** [comment]
Fixed in a PR.
