### ISSUE TITLE
[PE-D] long help

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-2/tp#193]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/ff30f975-1d80-4653-8fa9-7e4a13b10e8c.png)
help is way too wordy, condensing it will be better

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: SeanHoWB/ped#7

**Comment by Musfirahe0556596** [comment]
Won't fix.
