### ISSUE TITLE
[PE-D] unfinshed DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-2/tp#194]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/30cc8df9-c61b-4442-a8cd-bbe3adb5dcd9.png)
No rush, still got time anyways haha, do rmbr to update!

-------------
Labels: `severity.High` `type.DocumentationBug`
original: SeanHoWB/ped#8

**Comment by a1021492980** [comment]
#233 has Exercise-related features
