### ISSUE TITLE
[PE-D] font size

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-2/tp#195]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/3e6e12f1-3f89-4cc0-8a3f-8bad4c33437f.png)
very small words in diagram, consider making it bigger

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: SeanHoWB/ped#9

**Comment by Musfirahe0556596** [comment]
Fixed in #215
