### ISSUE TITLE
[PE-D] seq diag issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-2/tp#203]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/dc1e6302-5418-40a0-ad9a-769fe0b5989a.png)
nothing activates or deactivates werkit

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SeanHoWB/ped#12

**Comment by a1021492980** [comment]
fixed in #305
