### ISSUE TITLE
[PE-D] big chunk of info, split it up

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-2/tp#205]
![image.png](https://raw.githubusercontent.com/SeanHoWB/ped/main/files/f18fe02e-3b90-439f-90bd-6f1df70bc24f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SeanHoWB/ped#14

**Comment by Musfirahe0556596** [comment]
#223 fixes this
