### ISSUE TITLE
[PE-D] Remind the user to update their schedule accordingly if some plan is deleted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-2/tp#208]
![Screenshot 2022-04-01 at 5.41.05 PM.png](https://raw.githubusercontent.com/Wang-Jingwei/ped/main/files/174ba2dc-2a09-423b-80ea-d6f6c3cdde1c.png)
It's not a "bug" but a suggestion. As the figure shown above, I deleted the plan named "Grow my muscles" (not included in the figure due to size limit) but didn't update it in the schedule. When I exit and reopen the program it shows"Schedule file   not ok...." and automatically change the plan into rest day.

It would be better and clearer if you can remind the user to update their schedule accordingly if some plan is deleted:)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Wang-Jingwei/ped#1

**Comment by Musfirahe0556596** [comment]
Fixed in #218
