### ISSUE TITLE
update workout message bug

### ISSUE THREAD

**Issue by TianaiYan** [AY2122S2-CS2113T-T09-2/tp#245]
If a workout is update after one time, the message for the plan is also updated will not shown.

**Comment by alanlowzies** [comment]
- When updating a workout for the first time, the procedure is done properly
- When the same workout is updated subsequent times, the messages that show that the plans have been updated will not be shown.
  - However, the plans are actually updated. 

Lines to check out: 284 and 285 (master branch)
