### ISSUE TITLE
DG Write-up on Instructions for Manual Testing

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2122S2-CS2113T-T09-2/tp#286]

**Comment by Musfirahe0556596** [comment]
#285 contains instructions for manual testing for:
- Launching and shutdown of app
- Deleting a workout, creating a plan and listing plans.

**Comment by alanlowzies** [comment]
PR #290 contains the write up for the following:
- Creating a new workout
- Data saving

**Comment by a1021492980** [comment]
#305 contains the write up for:
1. All search relevant features.
2. Viewing exercises.

**Comment by Musfirahe0556596** [comment]
#296 contains the write up for:
1. Listing all workouts
2. Schedule related features

**Comment by Musfirahe0556596** [comment]
#301 contains the write up for:
1. Updating workout
2. Listing workouts `plan /details`
3. Deleting an existing plan
