### ISSUE TITLE
Create JUnit Test Cases for WorkoutList.java

### ISSUE THREAD

**Issue by emilysim00** [AY2122S2-CS2113T-T09-2/tp#39]
Write up JUnit test cases for the WorkoutList class; list function.

**Comment by emilysim00** [comment]
PR #38 has some JUnit tests for list workout function in WorkoutList.java

**Comment by Musfirahe0556596** [comment]
PR https://github.com/AY2122S2-CS2113T-T09-2/tp/pull/42 has some JUnit tests for delete workout function in WorkoutList.java

**Comment by Musfirahe0556596** [comment]
PR https://github.com/AY2122S2-CS2113T-T09-2/tp/pull/51 has some JUnit tests for update workout function in WorkoutList.java

**Comment by alanlowzies** [comment]
PR #61 has some JUnit tests for `workout /new` feature in WorkoutList.java.

**Comment by alanlowzies** [comment]
Closed with PR #61
