### ISSUE TITLE
Update UserGuide.md with more information

### ISSUE THREAD

**Issue by emilysim00** [AY2122S2-CS2113T-T09-2/tp#57]
User guide to describe and explain all the commands of the application.

**Comment by emilysim00** [comment]
PR #45

**Comment by emilysim00** [comment]
PR #55

**Comment by emilysim00** [comment]
PR #58

**Comment by Musfirahe0556596** [comment]
PR https://github.com/AY2122S2-CS2113T-T09-2/tp/pull/74 has documentation for the update workout function

**Comment by alanlowzies** [comment]
Related issue: #75

**Comment by alanlowzies** [comment]
Related issue: #68

**Comment by a1021492980** [comment]
PR #101  has documentation for the list exercise function and help feature

**Comment by emilysim00** [comment]
PR #117 has documentation for schedule features

**Comment by Musfirahe0556596** [comment]
PR #128 has documentation for create plan and list plans.

**Comment by a1021492980** [comment]
PR #129  has documentation for search exercise/workout/plan/all features

**Comment by emilysim00** [comment]
PR #140 contains suggestions given by CS2101 other group members

**Comment by alanlowzies** [comment]
PR #145 adds some new content to the UG, including:

- Add a warning to discourage users from directly modifying the local data files for the app.
- Change the warning (regarding the pipe character |) format to make it look more obvious.
- Add a list of recommended terminals to use.
- Add an FAQ on file loading issues.

**Comment by alanlowzies** [comment]
PR #146 adds the `plan /details` and `plan /delete` commands to the UG.

**Comment by Musfirahe0556596** [comment]
PR #221 adds improvements to the UG based on peer feedbacks

**Comment by Musfirahe0556596** [comment]
PR #225 adds instructions on displaying colours on Windows Terminal
